#!/bin/sh

BASE_DIR="$HOME/Video/Anime"
VIDEO_PLAYER="mpv"
FINDER="fzf"


# Use sed to remove the base directory from the list
all_animes=$(find "$BASE_DIR/" -maxdepth 1 -type d -printf '%f\n' | sed -n '2,$p')

choosen_anime=$(echo "$all_animes" | fzf --color=16 --prompt "Choose an anime: ")

# No anime was choosen
if [[ "$?" != "0" ]] 
then
    exit 1;
fi

all_episodes=$(find "$BASE_DIR/$choosen_anime/" -type f -printf '%f\n'| sort)

choosen_episode=$(echo -e "$all_episodes" | fzf --color=16 --prompt='Choose an episode: ')

# No episode was choosen
if [[ "$?" != "0" ]] 
then
    exit 1;
fi

# Gets the list of all episodes including and after the choosen one
episodes=$(echo -e "$all_episodes" |\
           sed -n "/$choosen_episode/,\$p" |\
           sed "s:^.*$:$BASE_DIR/$choosen_anime/&:g")

//FIXME: Play multiple files
episode=$(echo -e "$episodes" | head -1)

$VIDEO_PLAYER "$episode" & disown;
exit
