#!/bin/bash
# checapares - Procura por linhas iguais em pares de arquivos de texto
#
# Descricão:
# Verifica um arquivo checando se existem
# linhas iguais em outro (Usando grep).
# Caso sejam encontradas linha iguais, estas são impressas
# numeradas, a partir de 1, na saída padrão.
#
# Versão 1.0: Adicionado suporte as flags -h e -V
# Versão 1.1: Verifca se foram passados dois arquivos como argumento
# Versão 1.2: Mudança na lógica para uso de streams
# Versão 1.3: Flag para ordenar saída
# Versão 1.4: Adicionado suporte a várias flags

# Mensagem para flag -h
MENSAGEM_AJUDA="
Uso $(basename $0) [-h | -V ] -  Procura por linhas iguais em pares de arquivos de texto

    -h | --help     Mostra esta tela de ajuda e sai.
    -V | --version  Mostra a versão do programa e sai.
    -s | --sort     Ordena saída alfabeticamente

Descricão:
Verifica um arquivo checando se existem
linhas iguais em outro (Usando grep).
Caso sejam encontradas linha iguais, estas são impressas
numeradas, a partir de 1, na saída padrão.

Modo de uso:
checapares arquivo1.txt arquivo2.txt

Exemplo:
arquivo1.txt  arquivo2.txt
fulano        zezinho
ciclano       luisinho
beltrano      fulano

Saída esperada:
1: fulano
"

ordenar=0 # Deve ordenar a saída?


# Tratamento das opções de linha de comando
while test -n "$1"
do
    case "$1" in
        -s | --sort)
            ordenar=1
            # Realiza shift apenas se for uma flag
            shift
            ;;

        -h | --help)
            echo "$MENSAGEM_AJUDA"
            exit 0
            ;;

        -V | --version)
            # Imprime nome do programa
            echo -n "$(basename $0): "
            # Pega versão do programa diretamente do cabeçalho 
            grep "^# Versão" $0 | tail -1 | cut -d : -f 1 | sed "s/^# // g"
            exit 0
            ;;

        *)
            # Caso nenhuma flag seja passada, verifica número de argumentos
            [ $# -lt 1 ] && echo "$(basename $0): Número insuficiente de arquivos!" && exit 1
            # Quando o argumento não for uma flag, sai do loop
            break
            ;;
    esac
done

# Remove espaços extras -> Monta comando do grep -> Bash -> Numera linhas
resultado=$(sed -E "s/\s*$//g" $1 | sed -E "s/.*/grep \"&\" $2/" | bash)

# Ordena o resultado ( se desejado )
test "$ordenar" = 1 && resultado=$(echo $resultado | sort)

# Imprime resultado, com linhas numeradas
echo "$resultado" | cat -n
