#!/bin/bash
#
# cpu-status - Uses notify-send to show the top 10 most intensive processes
#              and their CPU usage
#

use_notification=0

case "$1" in 
    -n | --notification)
        use_notification=1
        ;;
    *)
        ;;
esac

processes=$(ps axch -o cmd:15,%cpu --sort=-%cpu | head )

if [ "$use_notification" == "1" ]; then
    notify-send --icon x -t 3000 "$processes" && exit 0
else
    echo "$processes" && exit 0
fi
