#!/bin/sh
#
# dev - List project directories with fzf and opens the selected one on tmux / vim
#
# github.com/fsmiamoto

selected_project=$(find $PROJECT_DIR -maxdepth 1 -type d,l -printf '%f\n' | sed -n '2,$p'| fzf -q "$1" --color=16 --select-1 --prompt='Choose a project: ')

if [ -n "$selected_project" ]; then
    # Substitutes . for - on selected_project
    session_name=$(echo $selected_project | tr \. - )
    tmux new-session -A -s "$session_name" -c "$PROJECT_DIR/$selected_project" 'tmux split-window -h -p 35; tmux split-window -v -p 60; tmux select-pane -L; $EDITOR .'
fi

