#!/bin/sh
#
# run - Executes a file
#

# Gets filename without full path
filename=$(basename "$1")
shift;
args=$@

# Extracts file extension
extension="${filename##*.}"

case "$extension" in
    "go")
        go run "$1"
        ;;
    "js")
        node "$1"
        ;;
    "py")
        python "$1"
        ;;
    "m")
        octave "$1"
        ;;
    "vhd")
        ghdl -a "$1"
        ;;
    "c")
        timestamp=$(date +%s)
        bin="/tmp/run-$timestamp"

        gcc $filename -o $bin
        $bin $args
        
        # Cleanup
        rm $bin 2>/dev/null
        unset bin timestamp
        ;;
    *)
        "$1"
esac

