#!/bin/bash
#
# shut - Script para mostrar opções de Desligar e Reiniciar
#
#

# Opções
opcoes="Shutdown\nRestart\nLock\nExit"

# Obtém escolha via dmenu
escolha=$(echo -e $opcoes | rofi-dmenu "Choose your destiny" )

case $escolha in
    "Shutdown") i3exit shutdown ;;
    "Restart") i3exit reboot ;;
    "Lock") i3exit lock;;
    "Exit") i3exit logout ;;
esac
    



