#!/bin/bash
#
# shut - Script for power management
# github.com/fsmiamoto
#
#

options="シャットダウン\n再起動\nスリップ\nロック\n出る"

chosen=$(echo -e $options | rofi-dmenu "電源" )

case $chosen in
    "シャットダウン") systemctl poweroff ;;
    "再起動") systemctl reboot ;;
    "スリップ") systemctl suspend;;
    "ロック") lock;;
    "出る") killall Xorg;;
esac
    



