#!/bin/bash
#
# spotify-controls - Outputs the right icon depending on the current status
# of Spotify using the polybar-spotify module
#
# Author: Francisco Miamoto
# github.com/fsmiamoto


# Determines if any output will be generated
OUTPUT=1

if [ -n "$1" ]
then
    case "$1" in
        # Quiet mode, useful for conditionals
        -q | --quiet)
            OUTPUT=0
            ;;
    esac
fi


# Output of spotify_status
# e.g: ' Artist: Music' or empty if Spotify is now running
spotify=$(python "$HOME/.config/polybar/polybar-spotify/spotify_status.py")

# If output of spotify_status is not empty...
if [ -n "$spotify" ] 
then
    # Gets Spotify Play or Pause icon
    symbol=$(echo $spotify | grep -o '^.')

    if [ "$symbol" = "▶" ]
    then
        test "$OUTPUT" = 1 && echo ""
        exit 0 
    else
        test "$OUTPUT" = 1 && echo "" 
        exit 0
    fi
else
    exit -1
fi

