#!/bin/bash
#
# sync-files - Sincroniza .vimrc e .bashrc entre Desktop e Notebook
#
# github.com/fsmiamoto

# Sync .bashrc
curl https://github.com && curl https://raw.githubusercontent.com/fsmiamoto/dotfiles/master/.bashrc > $HOME/.bashrc

# Sync .vimrc
curl https://github.com && curl https://raw.githubusercontent.com/fsmiamoto/dotfiles/master/.vimrc > $HOME/.vimrc

# Sync dos scripts 
cd $HOME/.scripts && git pull
