#!/bin/sh
#
# Get the current volume level
#
# github.com/fsmiamoto

if [[ "$(pulsemixer --get-mute)" == "0" ]]
then
    pulsemixer --get-volume | awk '{ msg = "vol " $1 "%"; print msg }'
else
    echo "muted"
fi
