#!/bin/bash
#
# weather - Imprime notificação com o tempo atual
#

# Pega variáves necessária para uso no cron
# Referência: https://unix.stackexchange.com/questions/111188/using-notify-send-with-cron#111190
if [ -r "$HOME/.dbus/Xdbus" ]; then
      . "$HOME/.dbus/Xdbus"
fi

# Pega previsão e filtra
previsao=$(w3m -dump wttr.in/Curitiba?lang=ja | head -7 | tail -5 | sed -E 's/^\s//g')

# Envia notificação
notify-send --icon x -t 3000 "$previsao"







