#!/bin/bash
#
# weather - Imprime notificação com o tempo atual
#

# Pega variáves necessária para uso no cron
# Referência: https://unix.stackexchange.com/questions/111188/using-notify-send-with-cron#111190
if [ -r "$HOME/.dbus/Xdbus" ]; then
      . "$HOME/.dbus/Xdbus"
fi

# Envia notificação
notify-send --icon term -t 3000 "<b>Tempo Atual:</b>" "<b>$(curl -s wttr.in/Curitiba?format=3 | head -7 | tail -5)</b>"






